name: Main
on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 15 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: msilb7-crypto-queries/L2TVL/optimism_app_net_flows.py
    - name: Running
      run: |
        echo "Running!"